# Generated by Django 6.0.1 on 2026-02-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='middletname',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
