# Generated by Django 5.2.1 on 2026-02-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_middletname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='middletname',
        ),
        migrations.AddField(
            model_name='member',
            name='middlename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
